import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import '../widget/menu_widget.dart';
import 'package:fwfh_webview/fwfh_webview.dart';

class PolicyPage extends StatelessWidget {
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.green,
        title: Text('Privacy Policy'),
        leading: MenuWidget(),
      ),
      body: Container(
        child: ListView(
          children: <Widget>[
            HtmlWidget('''
                  <h1>Privacy Policy</h1>
                  <p>Last updated: March 08, 2022</p>
                  n, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                   Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/" target="_blank">Privacy Policy Template</a>.</p>
                  <h1>Interpretation and Definitions</h1>
                  <h2>Interpretation</h2>
                   under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                  <h2>Definitions</h2>
                  <p>For the purposes of this Privacy Policy:</p>
                  <ul>
                  <li>
                  our Service or parts of our Service.</p>
                  </li>
                  <li>
                   or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                  </li>
                  <li>
                  mpany downloaded by You on any electronic device, named chushotelapp</p>
                  </li>
                  <li>
                  quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to chushotelapp.</p>
                  </li>
                  <li>
                  <p><strong>Country</strong> refers to:  Vietnam</p>
                  </li>
                  <li>
                  as a computer, a cellphone or a digital tablet.</p>
                  </li>
                  <li>
                  ified or identifiable individual.</p>
                  </li>
                  <li>
                  <p><strong>Service</strong> refers to the Application.</p>
                  </li>
                  <li>
                  ocesses the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                  </li>
                  <li>
                   generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                  </li>
                  <li>
                  or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                  </li>
                  </ul>
                  <h1>Collecting and Using Your Personal Data</h1>
                  <h2>Types of Data Collected</h2>
                  <h3>Personal Data</h3>
                  lly identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                  <ul>
                  <li>
                  <p>First name and last name</p>
                  </li>
                  <li>
                  <p>Usage Data</p>
                  </li>
                  </ul>
                  <h3>Usage Data</h3>
                  <p>Usage Data is collected automatically when using the Service.</p>
                   address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                  certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                   our Service or when You access the Service by or through a mobile device.</p>
                  <h3>Information Collected while Using the Application</h3>
                  on, We may collect, with Your prior permission:</p>
                  <ul>
                  <li>Information regarding your location</li>
                  <li>Information from your Device's phone book (contacts list)</li>
                  </ul>
                   customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
                  Your Device settings.</p>
                  <h2>Use of Your Personal Data</h2>
                  <p>The Company may use Personal Data for the following purposes:</p>
                  <ul>
                  <li>
                   the usage of our Service.</p>
                  </li>
                  <li>
                  user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                  </li>
                  <li>
                  iance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
                  </li>
                  <li>
                   SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                  </li>
                  <li>
                  rmation about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
                  </li>
                  <li>
                  ts to Us.</p>
                  </li>
                  <li>
                  aluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
                  </li>
                  <li>
                   purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
                  </li>
                  </ul>
                  <p>We may share Your personal information in the following situations:</p>
                  <ul>
                  mation with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
                  rsonal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                  affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                  th Our business partners to offer You certain products, services or promotions.</li>
                   otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                  tion for any other purpose with Your consent.</li>
                  </ul>
                  <h2>Retention of Your Personal Data</h2>
                  y for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                  age Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
                  <h2>Transfer of Your Personal Data</h2>
                  perating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                  formation represents Your agreement to that transfer.</p>
                  ata is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                  <h2>Disclosure of Your Personal Data</h2>
                  <h3>Business Transactions</h3>
                  rsonal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                  <h3>Law enforcement</h3>
                  Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                  <h3>Other legal requirements</h3>
                  such action is necessary to:</p>
                  <ul>
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  </li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                  </ul>
                  <h2>Security of Your Personal Data</h2>
                  o method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                  <h1>Children's Privacy</h1>
                  ly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                  tion and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                  <h1>Links to Other Websites</h1>
                  s. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                  acy policies or practices of any third party sites or services.</p>
                  <h1>Changes to this Privacy Policy</h1>
                  any changes by posting the new Privacy Policy on this page.</p>
                  rior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
                  . Changes to this Privacy Policy are effective when they are posted on this page.</p>
                  <h1>Contact Us</h1>
                  <p>
                  <ul>
                  <li>By email: kiedielezz@gmail.com</li>
                  </ul></p>
                ''',
                factoryBuilder: () => MyWidgetFactory(),),
            ]
          ),
        ),
    );    
  }
}

            class MyWidgetFactory extends WidgetFactory with WebViewFactory {
            // optional: override getter to configure how WebViews are built
            bool get webViewMediaPlaybackAlwaysAllow => true;
            String? get webViewUserAgent => 'My app';
          }